networks:
  default:
  kafka-net:
    external: true
    name: kafka-net

services:
  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${RESOURCE_SERVICE_DATABASE}
      POSTGRES_USER: ${RESOURCE_SERVICE_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${RESOURCE_SERVICE_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${SONG_SERVICE_DATABASE}
      POSTGRES_USER: ${SONG_SERVICE_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SONG_SERVICE_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  resource-service:
    build:
      context: .
      dockerfile: ./resource-service/Dockerfile
    environment:
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
        - kafka-net
        - default
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      resource-db:
        condition: service_healthy
      song-service:
        condition: service_healthy
      resource-processor:
        condition: service_healthy
      eureka-server:
        condition: service_started

  song-service:
    build:
      context: .
      dockerfile: ./song-service/Dockerfile
    ports:
      - "8081-8082:8081"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8081/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      song-db:
        condition: service_healthy
      eureka-server:
        condition: service_started

  resource-processor:
    build:
      context: .
      dockerfile: ./resource-processor/Dockerfile
    ports:
      - "8087:8087"
    env_file:
      - .env
    networks:
      - kafka-net
      - default
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8087/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_started

  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
    env_file:
      - .env
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: .
      dockerfile: ./gateway-service/Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:8085/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_started
      resource-service:
        condition: service_healthy
      song-service:
        condition: service_healthy