CREATE TYPE public."storage_entry_type" AS ENUM (
	'PERMANENT',
	'STAGING',
	'DEFAULT');

CREATE TABLE public.storage_entry (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	container_name varchar(255) NULL,
	"path" varchar(255) NULL,
	storage_type public."storage_entry_type" NULL,
	CONSTRAINT storage_entry_pkey PRIMARY KEY (id)
);

INSERT INTO public.storage_entry (container_name, "path", storage_type) VALUES('staging-resource-1', 'files', 'STAGING'::public."storage_entry_type");
INSERT INTO public.storage_entry (container_name, "path", storage_type) VALUES('permanent-resource-1', 'files', 'PERMANENT'::public."storage_entry_type");
INSERT INTO public.storage_entry (container_name, "path", storage_type) VALUES('default-fallback-resource-1', 'files', 'DEFAULT'::public."storage_entry_type");