spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: resource-service
              uri: lb://resource-service
              predicates:
                - Path=/resources/**
            - id: song-service
              uri: lb://song-service
              predicates:
                - Path=/songs/**
            - id: resource-processor
              uri: lb://resource-processor
              predicates:
                - Path=/resource-processor/**
            - id: storage-service
              uri: lb://storage-service
              predicates:
                - Path=/storages/**

server:
  port: ${GATEWAY_SERVER_PORT:8086}

eureka:
  instance:
    healthCheckUrlPath: "/actuator/health"
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_SERVICE_URL:http://localhost:8762/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  health:
    ssl:
      enabled: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE