spring:
  application:
    name: eureka-server

server:
  port: ${EUREKA_SERVER_PORT:8762}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_SERVICE_URL:http://localhost:8762/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  health:
    ssl:
      enabled: false

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF
