server:
  port: 9000
  servlet:
    session:
      cookie:
        name: AUTH_SERVER_SESSION

spring:
  application:
    name: auth-server

eureka:
  instance:
    healthCheckUrlPath: "/actuator/health"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_SERVER_SERVICE_URL:http://localhost:8762/eureka/}"
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    ssl:
      enabled: false
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}"

#logging:
#  level:
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE